version: "3"
services:
  postgres:
    container_name: launchql-ast-postgres
    image: pyramation/postgis
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./bin:/sql-bin
      - ./extensions:/sql-extensions
      - ./packages:/sql-packages
